### ISSUE TITLE
Things that can be removed

### ISSUE THREAD

**Issue by Zopieux** [prologin/envlive#1]
> ###### Originally posted 2015-11-12 17:47 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

- avahi stuff (multiple useless desktop apps in the menus)
- `knetattach`
- QtLinguist
- QtDesigner
- QDbusViewer

**Comment by ordiclic** [comment]
> ###### Originally posted 2015-11-13 18:46 by [ordiclic](https://bitbucket.org/ordiclic/) on Bitbucket

* Avahi is required for monodevelop
* knetattach is installed by oxygen-icons, required for lxqt
* the rest is now useful because it is installed with qt5-tools, required by qtcreator.

**Comment by ordiclic** [comment]
> ###### Originally posted 2015-11-13 18:47 by [ordiclic](https://bitbucket.org/ordiclic/) on Bitbucket

Solved.

**Comment by ordiclic** [comment]
> ###### Originally posted 2015-11-13 19:22 by [ordiclic](https://bitbucket.org/ordiclic/) on Bitbucket

Actually there is no knetattach anywhere, no need for removal.
