### ISSUE TITLE
Use make target instead of versionning boot-bg.png

### ISSUE THREAD

**Issue by Zopieux** [prologin/envlive#10]
> ###### Originally posted 2017-02-21 09:56 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

TODO:

- remove `/boot-bg.png` from git (gitignore would be a must)
- integrate the `boot-bg.YEAR.png` make target in the build process

This requires inkscape on the host building the image.

**Comment by multun** [comment]
> ###### Originally posted 2017-03-26 15:02 by [multun](https://bitbucket.org/multun/) on Bitbucket

solved by 57094a2
