### ISSUE TITLE
Things that are broken

### ISSUE THREAD

**Issue by Zopieux** [prologin/envlive#2]
> ###### Originally posted 2015-11-12 17:48 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

- `Outils système → htop` does nothing

**Comment by ordiclic** [comment]
> ###### Originally posted 2015-11-13 18:59 by [ordiclic](https://bitbucket.org/ordiclic/) on Bitbucket

Will be opened again after the DE/WM changing.

**Comment by multun** [comment]
works for me™
