### ISSUE TITLE
QtCreator

### ISSUE THREAD

**Issue by Zopieux** [prologin/envlive#4]
> ###### Originally posted 2015-11-12 17:54 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

There are many Qt related stuff that no one cares about in a Prologin contest context (see #1):
- QtLinguist
- QtDesigner
- QDbusViewer
 
But there is not the actual useful thing: the **QtCreator C/C++ IDE**.

**Comment by ordiclic** [comment]
> ###### Originally posted 2015-11-13 18:48 by [ordiclic](https://bitbucket.org/ordiclic/) on Bitbucket

It will be added in the next push.
