### ISSUE TITLE
Pre-configure eric6

### ISSUE THREAD

**Issue by Zopieux** [prologin/envlive#5]
> ###### Originally posted 2015-11-12 17:57 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

At first startup, eric6 displays an annoying massive configuration dialog no one cares about. We should embed the default settings in `~prologin/` so candidates are not bothered by this shit.

**Comment by Zopieux** [comment]
> ###### Originally posted 2015-11-12 18:06 by [Zopieux](https://bitbucket.org/Zopieux/) on Bitbucket

[This](http://ix.io/maV) is the `~/.config/Eric6/eric6.ini` file I obtained after clicking "ok" without changing anything. Adding an empty file does not work, it has to contain some properties to bypass the dialog.

**Comment by ordiclic** [comment]
> ###### Originally posted 2015-11-13 19:05 by [ordiclic](https://bitbucket.org/ordiclic/) on Bitbucket

eric6.ini has been added to the repo and image generation.
