### ISSUE TITLE
Browser proxy

### ISSUE THREAD

**Issue by robin-thoni** [prologin/envlive#9]
> ###### Originally posted 2016-02-16 23:25 by [roblowchon](https://bitbucket.org/roblowchon/) on Bitbucket

Add an invalid proxy (like 127.0.0.1) for installed browser: some regional centers provide a gateway by there own DHCP

**Comment by ordiclic** [comment]
> ###### Originally posted 2016-02-19 17:03 by [ordiclic](https://bitbucket.org/ordiclic/) on Bitbucket

Adding an invalid proxy prevents access to the demifinals site.

**Comment by robin-thoni** [comment]
> ###### Originally posted 2016-02-19 18:22 by [roblowchon](https://bitbucket.org/roblowchon/) on Bitbucket

Not if you exclude local addresses
